import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import Body from "../components/Body/Body";
import ScrollToTopBtn from "../components/Body/ScrollToTopBtn";
import classes from "../global_css/index.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={classes.body}>
        <Navbar />
        <img src={"/images/banner.JPG"} className={classes.image}></img>
        <h1 className={classes.recommendationLabel}>Fresh recommendations</h1>
        <Body />
        <ScrollToTopBtn></ScrollToTopBtn>
      </body>
    </>
  );
}
